name: santhom_connect
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_svg_provider: ^1.0.7
  grouped_list: ^5.1.2
  pin_code_fields: ^8.0.1
  intl: ^0.18.0
  dio: ^5.3.3
  firebase_performance: ^0.9.3+2
  flutter_secure_storage: ^9.0.0
  calendar_date_picker2: ^0.5.5
  flutter_cached_pdfview: ^0.4.2
  url_launcher: ^6.2.5
  flutter_html: 3.0.0-beta.2
  fluttertoast: ^8.2.4
  table_calendar: ^3.0.9
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img_whatsapp_image.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeMedium.ttf
          weight: 500
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: Canela
      fonts:
        - asset: assets/fonts/CanelaRegular.ttf
          weight: 400
    - family: SF Pro
      fonts:
        - asset: assets/fonts/SFProMedium.ttf
          weight: 500
